### ISSUE TITLE
Error with requirement wheel

### ISSUE THREAD

**Issue by jjshao** [cnr-isti-vclab/TagLab#10]
Hi! I'm working on some intertidal/underwater imagery at Universite Laval and have been having issues getting TagLab to run. I'm running it on Ubuntu 20.04.2 (downloaded on Windows 10) with Python 3.7.5 and NVCC 10.1. I'm running into issues with install.py where I cannot install wheel. But if I run ```pip3 install wheel```, wheel is successfully installed. I'm wondering if it's a problem with my own system because I also have Python 3.8.5 installed but have Python 3.7.5 installed over it in a virtual environment and am running install.py with ```python3.7 install.py``` I just thought I would reach out and see if you guys had any insights to what was happening, thanks!

```
Found NVCC version: 10.1
Torch for CUDA 10.1
GDAL version installed: 3.0.4
Coraline built correctly.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting wheel
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wheel/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wheel/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wheel/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wheel/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wheel/
  Could not fetch URL https://pypi.org/simple/wheel/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/wheel/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
ERROR: No matching distribution found for wheel
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Traceback (most recent call last):
  File "install.py", line 164, in <module>
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.7', '-m', 'pip', 'install', 'wheel']' returned non-zero exit status 1.
```

**Comment by alemuntoni** [comment]
Weird. 
Could you try to run `pip3.7 install wheel`? 
If the error is the same, it could be related with this: https://stackoverflow.com/questions/41328451/ssl-module-in-python-is-not-available-when-installing-package-with-pip3

**Comment by jjshao** [comment]
Thanks for the tips! I've looked into that link and am still getting the same error. ```pip3.7 install wheel``` also gives the same error.

I've tried this and can confirm that pip3.7, pip3, and pip are all using Python3.7: https://askubuntu.com/questions/1232273/how-to-set-pip3-working-for-python3-7-not-python3-8

**Comment by jjshao** [comment]
I've uninstalled and reinstalled Python and am now running 3.6.8, and it works! Thanks :)
