### ISSUE TITLE
Crashes when using any tool

### ISSUE THREAD

**Issue by such-chris** [cnr-isti-vclab/TagLab#104]
I am having a problem with TagLab crashing when using any of the segmentation tools. I can outline, or use the positive/negative click without issue, but as soon as you "commit" to your segmentation the program loads for a bit, then closes without a dialog. The 4-clicks segmentation tool loads and crashes upon the placement of the 4th click. 

This is happening on 2 separate Windows 11 machines. Both with CUDA 11.6 and has happened with both Python 3.8 and 3.9.

Below is the output from command prompt when TagLab crashes.

`C:\Users\User\Desktop\TagLab-main>python.exe TagLab.py
TagLab 2023.3.16
C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\rasterio\__init__.py:228: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
Constructing ResNet model...
Dilations: (2, 4)
Number of classes: 1
Number of Input Channels: 4
Initializing classifier: PSP
C:\Users\User\Desktop\TagLab-main\source\tools\DeepExtreme.py:140: RuntimeWarning: overflow encountered in exp
  pred = 1 / (1 + np.exp(-pred))
Traceback (most recent call last):
  File "C:\Users\User\Desktop\TagLab-main\source\QtTablePanel.py", line 216, in addBlob
    self.data = self.data.append(new_row, ignore_index=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'`

**Comment by maxcorsini** [comment]
Hi Chris, 

this problem is caused by new version of pandas. We are going to do a release to account specifically for this problem. 

Best,

**Comment by maxcorsini** [comment]
Dear Chris,

we have just do a release to fix the problems you mentioned. Please, let us know if all is ok.

Thank you

**Comment by such-chris** [comment]
The update works great, thanks so much for all your effort!

Aloha,
Chris
