### ISSUE TITLE
Problem launching Taglab

### ISSUE THREAD

**Issue by MelanieOrr23** [cnr-isti-vclab/TagLab#112]
Hi, I managed to get Taglab working on my machine last March but havent used it since then. I have tried to re-launch it a few days ago and I get these Error messages. Could you please help me trouble shoot it?

(taglab_env) C:\---\Desktop\TagLab-main>python taglab.py
Traceback (most recent call last):
  File "taglab.py", line 42, in <module>
    from source.QtAlignmentToolWidget import QtAlignmentToolWidget
  File "C:\---\Desktop\TagLab-main\source\QtAlignmentToolWidget.py", line 18, in <module>
    from source.Image import Image
  File "C:\---\Desktop\TagLab-main\source\Image.py", line 1, in <module>
    from source.Channel import Channel
  File "C:\---\Desktop\TagLab-main\source\Channel.py", line 22, in <module>
    import rasterio as rio
  File "C:\---\Anaconda3\envs\taglab_env\lib\site-packages\rasterio\__init__.py", line 9, in <module>
    from rasterio._base import gdal_version
ImportError: DLL load failed while importing _base: The specified module could not be found.

I have also tried the command update.py without any luck

(taglab_env) C:\---\Desktop\TagLab-main>update.py
Traceback (most recent call last):
  File "C:\---\Desktop\TagLab-main\update.py", line 4, in <module>
    import urllib.request
ImportError: No module named request

thank you for your help!

**Comment by cappelletto** [comment]
Hi,
I have seen similar issues with gdal 3.X versions with rasterio 1.2.X. Could you please post the output for "conda list"?
You could try reinstalling some of the dependencies related to rasterio. Maybe these links contain useful information:
- https://stackoverflow.com/questions/62137916/getting-an-import-error-when-importing-rasterio
- https://github.com/conda-forge/rasterio-feedstock/issues/240
