### ISSUE TITLE
Problem installing TagLab

### ISSUE THREAD

**Issue by hopeeliwilson** [cnr-isti-vclab/TagLab#131]
Hello, I have completed all of the steps to download TagLab. I have tried the final step in the process. Run "python.exe taglab.py" on Windows PowerShell. Then, I get this error message. Any help would be appreciated. Thanks for your help! 

TagLab 2023.5.17
Traceback (most recent call last):
  File "Q:\Hope\Taglab\TagLab-2023.5.17\taglab.py", line 4709, in <module>
    tool = TagLab()
  File "Q:\Hope\Taglab\TagLab-2023.5.17\taglab.py", line 436, in __init__
    self.project.loadDictionary(os.path.join(self.taglab_dir, self.default_dictionary))
  File "Q:\Hope\Taglab\TagLab-2023.5.17\source\Project.py", line 277, in loadDictionary
    self.dictionary_name = dictionary['Name']
KeyError: 'Name'

**Comment by Jordan-Pierce** [comment]
It looks like it's trying to load in a JSON file representing the default label dictionary, which is in the TagLab folder `dictionaries`, called `scripps.json`. 

Based on your error, it looks like your directory setup is causing the error. Running the following command has expectations:
```python
python TagLab.py
```
Such that `TagLab.py` has access to the folder `dictionaries`, but your paths look slightly different:
```python
Q:\Hope\Taglab\TagLab-2023.5.17\taglab.py
```

You should look at changing how you structure you folders; maybe have each TagLab version you use be it's own folder, which contains `TagLab.py` and `dictionaries`:
```python

TagLab_version_A\
   TagLab.py
   dictionaries
   .... (everything else)

TagLab_version_B\
   TagLab.py
   dictionaries
   .... (everything else)

TagLab_version_C\
   TagLab.py
   dictionaries
   .... (everything else)

```

Instead of doing this:
```python

TagLab\

   TagLab_version_A\
   TagLab.py
   dictionaries
   .... (everything else)

   TagLab_version_B\
   TagLab.py
   dictionaries
   .... (everything else)

   TagLab_version_C\
   TagLab.py
   dictionaries
   .... (everything else)

```

That **may** be the issue, but it's hard to tell. If that's not the issue, please report back!

**Comment by hopeeliwilson** [comment]
Hi Jordan,

Thanks for the quick response. I changed by directory and it is still giving me the same error message. 

TagLab 2023.5.17
Traceback (most recent call last):
  File "Q:\Hope\TagLab_version_A\taglab.py", line 4709, in <module>
    tool = TagLab()
  File "Q:\Hope\TagLab_version_A\taglab.py", line 436, in __init__
    self.project.loadDictionary(os.path.join(self.taglab_dir, self.default_dictionary))
  File "Q:\Hope\TagLab_version_A\source\Project.py", line 277, in loadDictionary
    self.dictionary_name = dictionary['Name']
KeyError: 'Name'
