### ISSUE TITLE
Automatic Classifier Issue / Creating Custom Network Issue

### ISSUE THREAD

**Issue by tiffmm3** [cnr-isti-vclab/TagLab#140]
Hello! I am trying to use the automatic classifier, but I am running into this error:

```
Traceback (most recent call last):
  File "TagLab.py", line 4492, in applyPreview
    self.classifier = MapClassifier(classifier_selected, self.project.labels)
  File "C:\Users\OliviaPC\Documents\TagLab-main\source\MapClassifier.py", line 72, in __init__
    self.net = self._load_classifier(classifier_info['Weights'])
  File "C:\Users\OliviaPC\Documents\TagLab-main\source\MapClassifier.py", line 99, in _load_classifier
    classifier.load_state_dict(torch.load(network_name, map_location=torch.device("cuda")))
  File "C:\Users\OliviaPC\miniconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DeepLab:
        size mismatch for decoder.last_conv.8.weight: copying a param with shape torch.Size([2, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 256, 1, 1]).
        size mismatch for decoder.last_conv.8.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([8]).

```

I am also running into an issue when attempting to create a custom network. Here are the steps I have taken so far:

1. Do the manual segmentation and classification of 10 maps. These are originally shapefiles which hold a field called Benthic_features that labels each shape as a coral type (ArcGIS Pro)
2. Export 10 tiff files (with a black background, each color in a file represents a new class/coral type. The coral type's color is NOT consistent across the tiff files. I am not sure if that's okay?)
3. Create a New Project > import 10 new maps (tiff files) > so now I can see all my maps in the "Layers" section
4. Then export my working areas as training dataset. File >Export > Export New Training DataSet (I'm not sure how to adjust the pixel size according to the map scale)
When I look into the three folders: training, validation, test > I see that there are only images in the validation and test folders and the 'label' folder within the validation folder and the test folders (they each have one) are filled with black PNGs. Does this mean they did not identify any labels? 
Another question: Is the training folder empty because I am supposed to upload the corresponding orthomosaics of the tiff files?

6. Haven't gotten to this step yet, but when I try to run the "Train your network" with my existing created training data, there's an error that says:
`Traceback (most recent call last):
  File "C:\Users\OliviaPC\Documents\TagLab-main\source\QtTYNWidget.py", line 200, in chooseDatasetFolder
    self.analyzeDataset()
  File "C:\Users\OliviaPC\Documents\TagLab-main\source\QtTYNWidget.py", line 373, in analyzeDataset
    target_classes, freq_classes = CoralsDataset.importClassesFromDataset(labels_folder, self.project_labels)
  File "C:\Users\OliviaPC\Documents\TagLab-main\models\coral_dataset.py", line 315, in importClassesFromDataset
    dict_freq[key] = float(dict_freq[key]) / float(total_pixels)
ZeroDivisionError: float division by zero`

I'm guessing this is because I didn't get any labels identified during the last step.

Thank you!

**Comment by maxcorsini** [comment]
Hi Tiffany,

first of all, when you import your label maps created in ArcGis check that they are aligned with the orthoimages (it may happen or not depending on the georeferenciation, TagLab manage georeference information but not use them to align the orthos).
To facilitate this you can use the trasparency to switch between the imported labels and the orthoimages.

The second issue that you may have is the resolution of your map. If the resolution is not high you can experience problems during the tiles generation. 

Finally, when you export the dataset, you need to re-set the area of export. I mean, the working area influences many options of TagLab but not the export of the dataset, for this purpose you need to indicate again the region of interests on the map. 

I hope that these suggestions help you.

All the best

**Comment by maxcorsini** [comment]
I forgot one important thing. Pay attention that the color you used in the tiff for the labels and the color of your dictionary in TagLab (you need to set a label color-label name dictionary for your project) are exactly the same.

Best,
Massimiliano

**Comment by tiffmm3** [comment]
> I forgot one important thing. Pay attention that the color you used in the tiff for the labels and the color of your dictionary in TagLab (you need to set a label color-label name dictionary for your project) are exactly the same.
> 
> Best, Massimiliano

Awesome, I will try all of this out, and may return with follow-up questions. Thank you Massimiliano!

**Comment by tiffmm3** [comment]
> I forgot one important thing. Pay attention that the color you used in the tiff for the labels and the color of your dictionary in TagLab (you need to set a label color-label name dictionary for your project) are exactly the same.
> 
> Best, Massimiliano

Hi again @maxcorsini, unfortunately I am still running into issues. Here's a run-down of what I did so far:

1. “Polygon to Raster” > Value Field = ‘Benthic_Features’ (the field that holds unique values for each coral type)
2. Manually changed the raster colors to match the color dictionary in Taglab

Could not get the rasters to export into tiff files while keeping the color values 
Also could not get them to have a black background?
5. Resolution: Export Raster > NoData value = 0 > Compression Type LZW
Makes a tiff file BUT it gets rid of the color values 

7. Re-do the color values by copying the raster symbology (one by one)
8. Add black background: Share > Export map > Geotiff 
9. For each tiff file, cut out the ocean and the Esri tags: Photoshop > crop

11. (Tested out one tiff file) Upload “New Map” to TagLab (no orthoimage, just the one tiff file)
12. Export > Training data
13. Check the folder > all the labels are black still :((
14. File > Train Your Network > the only classes recognized were black/background

Any ideas on how to fix the labeling problem?

**Comment by tiffmm3** [comment]
Unrelated to the custom network question previously posted^

I got the automatic classifier (Porites) working, but I am experiencing varying levels of accuracy. See below for examples. 

1) After running the classifier and saving the project- I try to open the project again and TagLab crashes (Not Responsive). This occurs every other time I use the classifier, how do I prevent this?

2) I am hoping to use the automatic classifier to build a training set to make a custom network. I was wondering if there are any tips/advice to achieving greater accuracy?
Porites classifier, .65 threshold
![Uploading Screenshot 2024-06-19 114753.png…]()

**Comment by maxcorsini** [comment]
Hi, I see the labels load in the Taglab's interface but this seems the image of the labels and not the labels imported as regions (I see black stuff instead of the orthoimage even if the transparency is set to 50%). To import the labels correctly you need to Add an  orthoimage, and then Import the Label Map corresponding to such orthoimage. Plase, let me know if this helps.

**Comment by tiffmm3** [comment]
Thank you @maxcorsini for the response! I attempted what you said above, but when I upload a label image it is very small in comparison to the orthomosaic. And the labels (which I checked are corresponding to the color dictionary) are all labeled one type, despite there being multiple.

Here are screenshots of the labeling issue: https://docs.google.com/document/d/1aawuAxCXUUehq_4mRMLlSF3YkmPnf9qyDJpgNMOQlok/edit

**Comment by tiffmm3** [comment]
So excited that the custom network worked!! I am now looking into ways to improve the model, looking at the results, do you @maxcorsini have any suggestions?

Number of epochs: 10
Learning rate: .00005
L2 Regularization: .0005
Batch size: 4
Accuracy: 0.598
Mean Intersection over Union: 0.534

![Screenshot 2024-06-28 155834](https://github.com/cnr-isti-vclab/TagLab/assets/171400444/0fda5b0a-360c-4d1c-abe3-3c16ed6744d6)

![Screenshot 2024-06-28 121915](https://github.com/cnr-isti-vclab/TagLab/assets/171400444/071c1de4-6444-4058-a7f9-92b83075e192)
