### ISSUE TITLE
TagLab crashing while starting network training

### ISSUE THREAD

**Issue by kidconcept** [cnr-isti-vclab/TagLab#169]
I'm trying to train a network in TagLab, I've segmented and categorized my orthomosiac, and exported the training dataset. When I try and train a network, TagLab crashes immediately. Here is the error message I get.

Traceback (most recent call last):
  File "/Applications/TagLab-main/TagLab.py", line 5112, in trainNewNetwork
    dataset_train_info, train_loss_values, val_loss_values = training.trainingNetwork(images_dir_train, labels_dir_train,
  File "/Applications/TagLab-main/models/training.py", line 264, in trainingNetwork
    datasetTrain.computeAverage()
  File "/Applications/TagLab-main/models/coral_dataset.py", line 385, in computeAverage
    sum = np.zeros((self.CROP_SIZE, self.CROP_SIZE, 3), dtype=np.float)
  File "/Users/mermaid-danny/miniconda3/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
zsh: abort      python3 TagLab.py

My training settings
<img width="1512" alt="Screenshot 2024-11-27 at 5 16 14 PM" src="https://github.com/user-attachments/assets/2d638309-5d83-4b66-8065-1e5eb5593f79">

My project
<img width="1512" alt="Screenshot 2024-11-27 at 5 16 14 PM" src="https://github.com/user-attachments/assets/2bd661eb-6702-460d-b7f7-143e62632cc9">

**Comment by maxcorsini** [comment]
Thank you to point out this problem. Fixed.

**Comment by kidconcept** [comment]
Thank you for your prompt commit, unfortunately I haven't been able to get the training working after pulling your update due to new and different way's it's crashing. 

I tried with my main data set, and it crashed this time while importing the Training data with the following error: 
`OverflowError: Python integer 256 out of bounds for uint8`

So I created a smaller project with just a single label as a test and this time it crashed while importing the training data with the following error: 
`Traceback (most recent call last):
  File "/Users/bluegreen/Projects/TagLab-main/source/QtTYNWidget.py", line 200, in chooseDatasetFolder
    self.analyzeDataset()
  File "/Users/bluegreen/Projects/TagLab-main/source/QtTYNWidget.py", line 373, in analyzeDataset
    target_classes, freq_classes = CoralsDataset.importClassesFromDataset(labels_folder, self.project_labels)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bluegreen/Projects/TagLab-main/models/coral_dataset.py", line 322, in importClassesFromDataset
    dict_freq[key] = float(dict_freq[key]) / float(total_pixels)
                     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero`

Any advice?

**Comment by maxcorsini** [comment]
The OverflowError is something unexpected. How many classes do you have ? Please, give us more details. 

Regarding the second error, this means that you want to train for a class that is not present in the training dataset. We will fix it in a next release by writing a message instead of crashing. 

Best

**Comment by kidconcept** [comment]
When you say train for a class that is not present in the training dataset, do you mean train for a class that isn't in the scripps dictionary? I'm attempting to train custom labels for corals that aren't present in the scripps dictionary. To answer your question about the Overflow Error I've got 26 classes in my dictionary, you can see almost all of them in the screenshot posted above. But I've been struggling to get the training working at all, even with only one class and a smaller ortho...

**Comment by maxcorsini** [comment]
I mean that some of the classes selected are not present in the training dataset (0.0% in your screenshot). Pay attention that if the amount of pixels of some classes with high probability the classifier will not learn how to recognize these classes.

**Comment by kidconcept** [comment]
I'm still struggling with this one, quite a while later. I tried again on my map but no luck. So I tried again on one of the included sample projects. Here's a link to that project file (plot18) and to the exported training data which all looks ok to me. When I go to train, TagLab crashes with the following error:

`
/Applications/TagLab-main/models/coral_dataset.py:30: UserWarning: Argument 'always_apply' is not valid and will be ignored.
  Spatter(always_apply=False, p=0.2, mean=(0.65, 0.65), std=(0.3, 0.3), gauss_sigma=(0.72, 0.72),
Traceback (most recent call last):
  File "/Applications/TagLab-main/TagLab.py", line 5095, in trainNewNetwork
    dataset_train_info, train_loss_values, val_loss_values = training.trainingNetwork(images_dir_train, labels_dir_train,
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/TagLab-main/models/training.py", line 261, in trainingNetwork
    datasetTrain = CoralsDataset(images_folder_train, labels_folder_train, labels_dictionary, target_classes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/TagLab-main/models/coral_dataset.py", line 81, in __init__
    self.custom_color_aug = augmentation_color(p=0.8)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/TagLab-main/models/coral_dataset.py", line 32, in augmentation_color
    PixelDropout(always_apply=False, p=0.2, dropout_prob=0.02, per_channel=0, drop_value=(0, 0, 0),
  File "/Users/danvallentyne/.pyenv/versions/3.11.11/lib/python3.11/site-packages/albumentations/core/validation.py", line 35, in custom_init
    config = dct["InitSchema"](**full_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danvallentyne/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for InitSchema
drop_value.float
  Input should be a valid number [type=float_type, input_value=(0, 0, 0), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.10/v/float_type
drop_value.tuple[float, float]
  Tuple should have at most 2 items after validation, not 3 [type=too_long, input_value=(0, 0, 0), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.10/v/too_long
zsh: abort      python TagLab.py
`

Files and screenshots:
https://www.dropbox.com/scl/fo/763rxcem334sqns3aicyo/AGRoKXgmRHEgI3tp0rpfms4?rlkey=ui6y9furkampyyf55ebifqaru&st=venvvc7w&dl=0
