### ISSUE TITLE
Error in export new training dataset

### ISSUE THREAD

**Issue by HughRunyan** [cnr-isti-vclab/TagLab#26]
I've tried messing around with what labels are eyeballed on and off, export area, some other stuff. I keep getting the error

```TagLab 0.7
Traceback (most recent call last):
  File "taglab.py", line 3423, in exportNewDataset
    new_dataset.convert_colors_to_labels(target_classes, self.project.labels)
  File "C:\Users\hughr\docs_local\TagLab\source\NewDataset.py", line 535, in convert_colors_to_labels
    idx = np.where((imglbl[:, :, 0] == class_colors[0]) & (imglbl[:, :, 1] == class_colors[1]) & (imglbl[:, :, 2] == class_colors[2]))
TypeError: 'Label' object is not subscriptable```

**Comment by mlopezp** [comment]
I am getting the same error. 
Seems related to the changes to label dictionary.
Is there a fix for this?
I tried going back to 0.6 but it won't launch saying that there is a new version available.

**Comment by HughRunyan** [comment]
I was told it will be fixed in impending 1.0 release. It's pulling from a
.get() object method, expecting a list of three RGB values, which
apparently returns another object, I haven't messed with it enough to fix
it but the answer is probably just to do a RGB_values = object.values or
object.data or something like that


On Wed, Feb 2, 2022 at 11:59 PM Mauricio Lopez ***@***.***>
wrote:

> I am getting the same error.
> Seems related to the changes to label dictionary.
> Is there a fix for this?
> I tried going back to 0.6 but it won't launch saying that there is a new
> version available.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cnr-2Disti-2Dvclab_TagLab_issues_26-23issuecomment-2D1028699166&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=ZtucxvevCJNhdUeM4U7-iAXhUcygSOsxu54eCbzLIAo&m=J3uTlawGsat8ZWER52_YqI5OAgpENRiXEHUVrgeuNoZEQYlk5eB_w1OOTx0qQnQ-&s=6adh6PTcsQm-fGNbQ0629wgfEJbJWuRffJjLsMRQKeg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADZFS3LKKKL4LVQIJQ2WZOTUZIYV3ANCNFSM5MH2IC6Q&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=ZtucxvevCJNhdUeM4U7-iAXhUcygSOsxu54eCbzLIAo&m=J3uTlawGsat8ZWER52_YqI5OAgpENRiXEHUVrgeuNoZEQYlk5eB_w1OOTx0qQnQ-&s=k1VVNLg8bKGTDUYqJur42qe7uBib8mupdHSJnCPZUy0&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=ZtucxvevCJNhdUeM4U7-iAXhUcygSOsxu54eCbzLIAo&m=J3uTlawGsat8ZWER52_YqI5OAgpENRiXEHUVrgeuNoZEQYlk5eB_w1OOTx0qQnQ-&s=fkBvnMcvjqkazMsovOipj2hEzw1HAHi8xLNjrEdrlEw&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=ZtucxvevCJNhdUeM4U7-iAXhUcygSOsxu54eCbzLIAo&m=J3uTlawGsat8ZWER52_YqI5OAgpENRiXEHUVrgeuNoZEQYlk5eB_w1OOTx0qQnQ-&s=OhHo4VY72qsGagrSpd9wP1c08N63WV_mYUlIGzIdxfI&e=>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Hugh Runyan (he/him/his)
Sandin Coral Ecology Lab/Kuester Cultural Heritage Engineering Initiative
Scripps Institution of Oceanography/UCSD

**Comment by mlopezp** [comment]
Thanks.
I don't have a ton of experience with Python so guess I will wait for the update.

**Comment by maxcorsini** [comment]
Hi all, 
unfortunately the introduction of the custom dictionary creates several issues. 
We are preparing a new release that fix all these problems and add new several new features. 
We hope to have it ready soon.
