### ISSUE TITLE
Runtime Error: QPixmap

### ISSUE THREAD

**Issue by jjshao** [cnr-isti-vclab/TagLab#56]
Hello,

I have been having trouble running TagLab today even though I have previously opened it before. I have uninstalled and reinstalled all the packages on my computer and in different Python environments. I have included the entire error message below. Is there anything I can do to get around this and run the program?

Thanks.

```
Traceback (most recent call last):
  File "/Users/jshao/Desktop/TagLab-main/TagLab.py", line 4578, in <module>
    tool = TagLab()
  File "/Users/jshao/Desktop/TagLab-main/TagLab.py", line 287, in __init__
    self.viewerplus = QtImageViewerPlus(self.taglab_dir)
  File "/Users/jshao/Desktop/TagLab-main/source/QtImageViewerPlus.py", line 128, in __init__
    self.tools = Tools(self)
  File "/Users/jshao/Desktop/TagLab-main/source/Tools.py", line 34, in __init__
    self.scribbles = Scribbles(self.scene)
  File "/Users/jshao/Desktop/TagLab-main/source/tools/Scribbles.py", line 32, in __init__
    self.setCustomCursor()
  File "/Users/jshao/Desktop/TagLab-main/source/tools/Scribbles.py", line 47, in setCustomCursor
    pxmap = QPixmap(cursor_size, cursor_size)
TypeError: arguments did not match any overloaded call:
  QPixmap(): too many arguments
  QPixmap(int, int): argument 1 has unexpected type 'float'
  QPixmap(QSize): argument 1 has unexpected type 'float'
  QPixmap(str, format: str = None, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.ImageConversionFlag.AutoColor): argument 1 has unexpected type 'float'
  QPixmap(List[str]): argument 1 has unexpected type 'float'
  QPixmap(QPixmap): argument 1 has unexpected type 'float'
  QPixmap(Any): too many arguments
```

**Comment by maxcorsini** [comment]
The cast to integer does not work. This seems a Python problem. Which version of Python are you using  ?

**Comment by jjshao** [comment]
I am using Python 3.10.6

**Comment by jjshao** [comment]
You're right! It was a Python problem. It is now opening with Python3.9.13

Thank you! I'm sorry for the bother.
