### ISSUE TITLE
"Maps editor" Not available

### ISSUE THREAD

**Issue by ihuanh** [cnr-isti-vclab/TagLab#59]
After update to ver 2022.10.13, TagLab crush when selecting the "Maps Editor" in Project.
How can I fix this problem?

--
C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\rasterio\__init__.py:226: NotGeoreferencedWarning: Dataset has no geotransform set. The identity matrix may be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
Traceback (most recent call last):
  File "rasterio\_base.pyx", line 216, in rasterio._base.DatasetBase.__init__
  File "rasterio\_shim.pyx", line 78, in rasterio._shim.open_dataset
  File "rasterio\_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: : No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "taglab.py", line 3076, in openProjectEditor
    self.projectEditor = QtProjectEditor(self.project, parent=self)
  File "C:\Users\user\Desktop\TagLab-main\source\QtProjectEditor.py", line 65, in __init__
    self.fillMaps()
  File "C:\Users\user\Desktop\TagLab-main\source\QtProjectEditor.py", line 86, in fillMaps
    self.text.append("<b>Map georeference information</b>" + " : <br><pre>" + self.georefAvailable(img.georef_filename) + "</pre>")
  File "C:\Users\user\Desktop\TagLab-main\source\QtProjectEditor.py", line 152, in georefAvailable
    img = rio.open(path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\rasterio\env.py", line 433, in wrapper
    return f(*args, **kwds)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\rasterio\__init__.py", line 226, in open
    s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio\_base.pyx", line 218, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: : No such file or directory

**Comment by maxcorsini** [comment]
Thank you to report this bug. We have fixed it and created a new release.
