### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by Maria-Lambre** [cnr-isti-vclab/TagLab#86]
Hi,
I'm trying to install Taglab in a Windows 10. I followed all the steps but when I try to open it in the terminal I receive the following message:

c:\TagLab>taglab.py
Traceback (most recent call last):
  File "C:\TagLab\TagLab.py", line 30, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

I thought it was a package that was missing, so I installed the package and tried to open taglab again but another message appeared indicating another package was missing. I continued downloaading the packages and after I installed all of them nothing happened because I’m still unable to open taglab. However, I installed taglab in another computer in October 2022 and everything went fine and I’m still able to open it in that computer, but I can’t install it in another PC (I tried in 2) because that message always appears. Could it be something with the new released version? How can I solve this problem? Or the newest Python version? I’d really appreciate your help.

**Comment by alemuntoni** [comment]
Could you please share the python version you are using and what is printed when running install.py?

**Comment by Maria-Lambre** [comment]
Hi! Thank you for your response.
The python version is Python 3.11(64-bit) and this is what's printed when running install.py:

c:\TagLab-main>install.py
Found NVCC version: 11.6
Torch 1.12.1 for CUDA 11.6
Requirement already satisfied: wheel in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (0.38.4)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: pyqt5 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (5.15.8)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pyqt5) (12.11.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pyqt5) (5.15.2)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: scikit-image in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (0.19.3)
Requirement already satisfied: numpy>=1.17.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (1.24.1)
Requirement already satisfied: scipy>=1.4.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (1.10.0)
Requirement already satisfied: networkx>=2.2 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (3.0)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (9.4.0)
Requirement already satisfied: imageio>=2.4.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (2.25.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (2023.1.23.1)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (1.4.1)
Requirement already satisfied: packaging>=20.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image) (23.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Collecting scikit-learn
  Downloading scikit_learn-1.2.1-cp311-cp311-win_amd64.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 29.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.3 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.24.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.10.0)
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB ? eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.2.0 scikit-learn-1.2.1 threadpoolctl-3.1.0

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: pandas in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.1)
Requirement already satisfied: six>=1.5 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: opencv-python in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (4.7.0.68)
Requirement already satisfied: numpy>=1.21.2 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from opencv-python) (1.24.1)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Collecting matplotlib
  Downloading matplotlib-3.7.0-cp311-cp311-win_amd64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 27.2 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp311-cp311-win_amd64.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.0/163.0 kB ? eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.38.0-py3-none-any.whl (965 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 965.4/965.4 kB ? eta 0:00:00
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp311-cp311-win_amd64.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.4/55.4 kB ? eta 0:00:00
Requirement already satisfied: numpy>=1.20 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.24.1)
Requirement already satisfied: packaging>=20.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Installing collected packages: kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.0.7 cycler-0.11.0 fonttools-4.38.0 kiwisolver-1.4.4 matplotlib-3.7.0

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Collecting albumentations
  Downloading albumentations-1.3.0-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.5/123.5 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.11.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from albumentations) (1.24.1)
Requirement already satisfied: scipy in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from albumentations) (1.10.0)
Requirement already satisfied: scikit-image>=0.16.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from albumentations) (0.19.3)
Collecting PyYAML
  Downloading PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.2/143.2 kB 8.9 MB/s eta 0:00:00
Collecting qudida>=0.0.4
  Downloading qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting opencv-python-headless>=4.1.1
  Downloading opencv_python_headless-4.7.0.72-cp37-abi3-win_amd64.whl (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 54.7 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=0.19.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from qudida>=0.0.4->albumentations) (1.2.1)
Collecting typing-extensions
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Requirement already satisfied: networkx>=2.2 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image>=0.16.1->albumentations) (3.0)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image>=0.16.1->albumentations) (9.4.0)
Requirement already satisfied: imageio>=2.4.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image>=0.16.1->albumentations) (2.25.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image>=0.16.1->albumentations) (2023.1.23.1)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image>=0.16.1->albumentations) (1.4.1)
Requirement already satisfied: packaging>=20.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-image>=0.16.1->albumentations) (23.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (3.1.0)
Installing collected packages: typing-extensions, PyYAML, opencv-python-headless, qudida, albumentations
Successfully installed PyYAML-6.0 albumentations-1.3.0 opencv-python-headless-4.7.0.72 qudida-0.0.4 typing-extensions-4.5.0

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: shapely in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (2.0.0)
Requirement already satisfied: numpy>=1.14 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from shapely) (1.24.1)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Collecting pycocotools
  Downloading pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: matplotlib>=2.1.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pycocotools) (3.7.0)
Requirement already satisfied: numpy in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from pycocotools) (1.24.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\melam\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools) (1.16.0)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml) ... done
  Created wheel for pycocotools: filename=pycocotools-2.0.6-cp311-cp311-win_amd64.whl size=76234 sha256=c9717f0165722f3d5dcf6981b4f554ff874bdde23cb812b9e68492d0fe2ef5c1
  Stored in directory: c:\users\melam\appdata\local\pip\cache\wheels\a4\4b\90\321ef9b281984114643dc19e40d8e1d65b651a42a4fe75ef15
Successfully built pycocotools
Installing collected packages: pycocotools
Successfully installed pycocotools-2.0.6

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\TagLab-main\install.py", line 234, in <module>
    list_args.append(torch_extra_argument1, torch_extra_argument2)
TypeError: list.append() takes exactly one argument (2 given)

c:\TagLab-main>taglab.py
Incompatible version between pytorch, cuda and python.
Knowing working version combinations are
: Cuda 10.0, pytorch 1.0.0, python 3.6.8No module named 'torch'
Traceback (most recent call last):
  File "C:\TagLab-main\TagLab.py", line 54, in <module>
    import source.RasterOps as rasterops
  File "C:\TagLab-main\source\RasterOps.py", line 6, in <module>
    from osgeo import gdal, osr
ModuleNotFoundError: No module named 'osgeo'

**Comment by Maria-Lambre** [comment]
Good morning, have you found a way to solve the problem? Thanks again

**Comment by alemuntoni** [comment]
As you can see [here](https://github.com/cnr-isti-vclab/TagLab#software-requirements), right now the supported python versions are 3.8 and 3.9. We are working to support python 3.10, which will be available soon.

**Comment by maxcorsini** [comment]
alemuntoni finishes the new support. Now, TagLab works with Python 3.8, 3.9 and 3.10 and with the modern versions of pytorch.

**Comment by Maria-Lambre** [comment]
Thank you very much for your response. I've just tried it with the Python 3.9 version and it didn't work either. This is what is printed when I try to run Taglab after installing it:


c:\Aplicaciones de TFG\TagLab>TagLab.py
Traceback (most recent call last):
  File "C:\Aplicaciones de TFG\TagLab\TagLab.py", line 42, in <module>
    from source.QtAlignmentToolWidget import QtAlignmentToolWidget
  File "C:\Aplicaciones de TFG\TagLab\source\QtAlignmentToolWidget.py", line 18, in <module>
    from source.Image import Image
  File "C:\Aplicaciones de TFG\TagLab\source\Image.py", line 1, in <module>
    from source.Channel import Channel
  File "C:\Aplicaciones de TFG\TagLab\source\Channel.py", line 22, in <module>
    import rasterio as rio
ModuleNotFoundError: No module named 'rasterio'

**Comment by Maria-Lambre** [comment]
Good evening, I'm still having problems installing Taglab and I don't know how to fix it. Any help would be greatly appreciated

**Comment by maxcorsini** [comment]
Try to re-launch install.py and let us know if this solve it.

**Comment by Maria-Lambre** [comment]
It worked!! Thank you so much for your good support :)
