### ISSUE TITLE
Opens, but Consistently Crashes within 5 Minutes

### ISSUE THREAD

**Issue by TNCSTXRocky** [cnr-isti-vclab/TagLab#89]
Hi All,

I've just downloaded TagLab and am having a few issues. My first (more minor) issue is that I am unable to open TagLab without using Command Prompt. The second issue is that when I do open TagLab it unexpectedly quits within 5 minutes, every time. Any thoughts or troubleshooting suggestions are greatly appreciated! Thank you.

c:\TagLab-main>py taglab.py
TagLab 2023.3.8
C:\Python\lib\site-packages\rasterio\__init__.py:228: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
CUDA NOT AVAILABLE!
CUDA NOT AVAILABLE!
CUDA NOT AVAILABLE!
C:\Python\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "c:\TagLab-main\taglab.py", line 786, in autosave
    filename, file_extension = os.path.splitext(self.project.filename)
  File "C:\Python\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
**TypeError: expected str, bytes or os.PathLike object, not NoneType**

**Comment by maxcorsini** [comment]
It apperas that you are using GPU version of pytorch without CUDA. Have you installed CUDA on your machine ? IF your machine do not have a GPU you need to install the CPU version of TagLab.

**Comment by TNCSTXRocky** [comment]
Hi Massimiliano,

Thanks for the prompt reply and information. I was under the impression that CUDA had been installed, but it looks like the app won't fully launch on my laptop. I'll try to install the CPU version and see if that will work. Thank you!
