### ISSUE TITLE
Problem installing taglab again

### ISSUE THREAD

**Issue by Maria-Lambre** [cnr-isti-vclab/TagLab#94]
Hi, 
I'm trying to install Taglab in another computer without NVCC this time and I'm having the same problem I had before with the package "rasterio". There seems to be an error with pycocotools too and I downloaded and reinstalled it again from the link you suggested in the issue nº 21,  but unfortunately is still not working. 

This is the error I get:

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\TagLab\install.py", line 231, in <module>
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', 'pycocotools']' returned non-zero exit status 1.

c:\TagLab>taglab.py
Traceback (most recent call last):
  File "C:\TagLab\TagLab.py", line 42, in <module>
    from source.QtAlignmentToolWidget import QtAlignmentToolWidget
  File "C:\TagLab\source\QtAlignmentToolWidget.py", line 18, in <module>
    from source.Image import Image
  File "C:\TagLab\source\Image.py", line 1, in <module>
    from source.Channel import Channel
  File "C:\TagLab\source\Channel.py", line 22, in <module>
    import rasterio as rio
ModuleNotFoundError: No module named 'rasterio'

c:\TagLab>install.py
Impossible to run "nvcc --version" command. CUDA seems to be not installed.
Something is wrong with NVCC. Do you want to install the CPU version of pythorch? [Y/n]

I wrote "Y" for yes and when I install the CPU version I get the problem with rasterio again. I don't know how to solve this and any help would be much appreciated.

Thank you
María

**Comment by maxcorsini** [comment]
Hi again,

if the building of pycocotools fails the installation stops. Hence, some packages are not installed (like rasterio). 

If your OS is Windows, download the Microsoft BUild Tools here:

https://visualstudio.microsoft.com/visual-cpp-build-tools/

Then, after lauch this setup choose the C++ option and install what is suggested. 

Then, re-launch the installation script of TagLab. This should solve.
